---
- name: Setup ccmall infrastructure
  hosts: all
  become: true
  gather_facts: yes
  vars:
    app_name: ccmall
    app_user: ccmall
    app_dir: /opt/ccmall
    app_module: "app.main:app"
    app_port: 8000
    app_repo: "https://github.com/hacksungboo/ccmall-omni-backup"
    app_branch: main
    ccmall_domain: "bobobobo.store"
    certbot_email: "gkrtjdqn@gmail.com"

  roles:
    - setting