- name: PostgreSQL 설치 및 S3 복구 + Tailscale 연결
  hosts: all
  become: true

  vars:
    # [수정] scheduler.py에서 저장한 실제 S3 경로 지정
    backup_s3_path: "backups/full_db_backup.sql"   ### sql파일 경로 및 이름 바뀌면 "backups/full_db_backup.sql" 리펙토링 해야합니다
    db_name: "ccmall_db"
    db_user: "ccmall_user"
    db_password: "user1"

  tasks:
    - name: 1. PostgreSQL 설치
      dnf:
        name: [postgresql15, postgresql15-server, awscli]
        state: present

    - name: 2. PostgreSQL 초기화
      shell: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: 3. PostgreSQL 서비스 시작
      systemd:
        name: postgresql
        state: started
        enabled: true

    - name: 4. listen_addresses 설정
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^#?listen_addresses'
        line: "listen_addresses='*'"

    - name: 5. pg_hba.conf 허용 추가
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: "host all all 0.0.0.0/0 md5"

    - name: 6. PostgreSQL 재시작
      systemd:
        name: postgresql
        state: restarted

    - name: 7. DB User 생성
      become_user: postgres
      shell: |
        psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';" || true

    - name: 8. Database 생성
      become_user: postgres
      shell: |
        psql -lqt | cut -d \| -f 1 | grep -qw {{ db_name }} || \
        createdb -O {{ db_user }} {{ db_name }}

    - name: 9. S3 백업 다운로드 
      shell: |
        aws s3 cp s3://{{ s3_bucket_name }}/{{ backup_s3_path }} /tmp/full_db_backup.sql  

    - name: 10. 백업 파일 권한 설정
      file:
        path: "/tmp/full_db_backup.sql"
        owner: postgres
        group: postgres
        mode: '0644'

    - name: 11. PostgreSQL 데이터 복구
      become_user: postgres
      shell: |
        psql {{ db_name }} < /tmp/full_db_backup.sql

    - name: 12. Tailscale 설치
      shell: curl -fsSL https://tailscale.com/install.sh | sh
      args:
        creates: /usr/bin/tailscale

    - name: 13. tailscaled 서비스 시작
      systemd:
        name: tailscaled
        state: started
        enabled: true

    - name: 14. Tailscale VPN 연결
      shell: tailscale up --authkey {{ tailscale_auth_key }} --accept-dns=false
      async: 60
      poll: 0 

    - name: 15. 로컬 database.py IP 자동 변경 (경로 수정 완료)
      delegate_to: localhost
      lineinfile:
        path: "../../app/core/database.py" 
        regexp: 'DB_HOST = os.getenv\("DB_HOST", .*\)'
        line: 'DB_HOST = os.getenv("DB_HOST", "{{ ansible_host }}")'